name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  dist-linux:
    name: Dist (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Package
        run: tar czvf hex-Linux-x86_64.tar.gz target/release/hex
      - uses: actions/upload-artifact@v2
        with:
          name: dist-linux
          path: hex-Linux-x86_64.tar.gz
  
  dist-windows:
    name: Dist (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Package
        run: 7z a hex-Windows-x86_64.zip target/release/hex
      - uses: actions/upload-artifact@v2
        with:
          name: dist-windows
          path: hex-Windows-x86_64.zip
  
  dist-macos:
    name: Dist (Mac OS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Package
        run: tar czvf hex-MacOS-x86_64.tar.gz target/release/hex
      - uses: actions/upload-artifact@v2
        with:
          name: dist-macos
          path: hex-MacOS-x86_64.tar.gz

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - dist-linux
      - dist-windows
      - dist-macos
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist-linux
          path: ./dist
      - uses: actions/download-artifact@v2
        with:
          name: dist-windows
          path: ./dist
      - uses: actions/download-artifact@v2
        with:
          name: dist-macos
          path: ./dist
      - uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: |
            dist/hex-Linux-x86_64.tar.gz
            dist/hex-Windows-x86_64.zip
            dist/hex-MacOS-x86_64.tar.gz
            LICENSE
            Changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: aszecsei/hex